import { Geist, Geist_Mono, Public_Sans } from "next/font/google";
// import ClientLayout from './ClientLayout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const publicSans = Geist({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mantis Admin Dashboard",
  description: "Generated by SHAN",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="./logo/image.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${publicSans.variable} antialiased `}>
        {/* <ClientLayout> */}
          {children}
        {/* </ClientLayout> */}
      </body>
    </html>
  );
}
